TABLE_SCHEMA = [
                {'name': 'track__id', 'type': 'STRING'},
                {'name': 'track__name', 'type': 'STRING'},
                {'name': 'isrc', 'type': 'STRING'},
                {'name': 'uri', 'type': 'STRING'},
                {'name': 'album__name', 'type': 'STRING'},
                {'name': 'album__code', 'type': 'STRING'},
                {'name': 'album__artist', 'type': 'STRING'},
                {'name': 'track__artists', 'type': 'STRING'},
                {'name': 'streams', 'type': 'INTEGER'},
                {'name': 'stream_seconds_avg', 'type': 'FLOAT'},
                {'name': 'y_discovery_flag', 'type': 'INTEGER'},
                {'name': 'n_discovery_flag', 'type': 'INTEGER'},
                {'name': 'y_streams_online', 'type': 'INTEGER'},
                {'name': 'n_streams_online', 'type': 'INTEGER'},
                {'name': 'y_shuffle', 'type': 'INTEGER'},
                {'name': 'n_shuffle', 'type': 'INTEGER'},
                {'name': 'y_repeat_play', 'type': 'INTEGER'},
                {'name': 'n_repeat_play', 'type': 'INTEGER'},
                {'name': 'source__artist', 'type': 'INTEGER'},
                {'name': 'source__collection', 'type': 'INTEGER'},
                {'name': 'source__others_playlist', 'type': 'INTEGER'},
                {'name': 'source__album', 'type': 'INTEGER'},
                {'name': 'source__radio', 'type': 'INTEGER'},
                {'name': 'source__others', 'type': 'INTEGER'},
                {'name': 'device__personal_computer', 'type': 'INTEGER'},
                {'name': 'device__cell_phone', 'type': 'INTEGER'},
                {'name': 'device__tablet', 'type': 'INTEGER'},
                {'name': 'device__smart_tv', 'type': 'INTEGER'},
                {'name': 'device__connected_audio', 'type': 'INTEGER'},
                {'name': 'device__gaming_console', 'type': 'INTEGER'},
                {'name': 'device__car_application', 'type': 'INTEGER'},
                {'name': 'device__others', 'type': 'INTEGER'},
                {'name': 'os__windows', 'type': 'INTEGER'},
                {'name': 'os__android', 'type': 'INTEGER'},
                {'name': 'os__ios', 'type': 'INTEGER'},
                {'name': 'os__mac', 'type': 'INTEGER'},
                {'name': 'os__linux', 'type': 'INTEGER'},
                {'name': 'browser', 'type': 'INTEGER'},
                {'name': 'os__others', 'type': 'INTEGER'},
                {'name': 'account__paid', 'type': 'INTEGER'},
                {'name': 'account__ad', 'type': 'INTEGER'},
                {'name': 'account__trial', 'type': 'INTEGER'},
                {'name': 'account__partner', 'type': 'INTEGER'},
                {'name': 'account__partner_free', 'type': 'INTEGER'},
                {'name': 'account__deleted', 'type': 'INTEGER'},
                {'name': 'gender__male', 'type': 'INTEGER'},
                {'name': 'gender__female', 'type': 'INTEGER'},
                {'name': 'gender__unknown', 'type': 'INTEGER'},
                {'name': 'age__0_17', 'type': 'INTEGER'},
                {'name': 'age__18_22', 'type': 'INTEGER'},
                {'name': 'age__23_27', 'type': 'INTEGER'},
                {'name': 'age__28_34', 'type': 'INTEGER'},
                {'name': 'age__35_44', 'type': 'INTEGER'},
                {'name': 'age__45_59', 'type': 'INTEGER'},
                {'name': 'age__60_150', 'type': 'INTEGER'},
                {'name': 'age__unknown', 'type': 'INTEGER'},
                {'name': 'free_saves', 'type': 'INTEGER'},
                {'name': 'premium_saves', 'type': 'INTEGER'},
                {'name': 'skips', 'type': 'INTEGER'},
                {'name': 'date', 'type': 'DATE'}, ]

NAMECOLUMNS_SUM = ['track__id', 'track__name', 'isrc', 'uri', 'album__name', 'album__code', 'album__artist',
                   'track__artists', 'streams', 'stream_seconds_avg', 'y_discovery_flag', 'n_discovery_flag',
                   'y_streams_online', 'n_streams_online', 'y_shuffle', 'n_shuffle', 'y_repeat_play', 'n_repeat_play',
                   'source__artist', 'source__collection', 'source__others_playlist', 'source__album', 'source__radio',
                   'source__others', 'device__personal_computer', 'device__cell_phone', 'device__tablet',
                   'device__smart_tv', 'device__connected_audio', 'device__gaming_console', 'device__car_application',
                   'device__others', 'os__windows', 'os__android', 'os__ios', 'os__mac', 'os__linux', 'browser',
                   'os__others', 'account__paid', 'account__ad', 'account__trial',	'account__partner',
                   'account__partner_free', 'account__deleted', 'gender__male', 'gender__female', 'gender__unknown',
                   'age__0_17', 'age__18_22', 'age__23_27', 'age__28_34', 'age__35_44', 'age__45_59', 'age__60_150',
                   'age__unknown', 'country', 'free_saves', 'premium_saves', 'skips', 'date']
