NAME_COLUMNS_POST = ['name', 'nickname', 'post_url', 'post_type', 'post_score','post_like', 'post_comment',
                     'date_post', 'date_extract']
TABLE_SCHEMA_POST_30 =[
    {'name': 'account_id', 'type': 'STRING'},
    {'name': 'account_name', 'type': 'STRING'},
    {'name': 'account_handle', 'type': 'STRING'},
    {'name': 'account_subscriber', 'type': 'INTEGER'},
    {'name': 'account_profile_picture', 'type': 'STRING'},
    {'name': 'account_url', 'type': 'STRING'},
    {'name': 'account_verified', 'type': 'BOOL'},
    {'name': 'account_language', 'type': 'STRING'},
    {'name': 'post_type', 'type': 'STRING'},
    {'name': 'post_description', 'type': 'STRING'},
    {'name': 'post_url', 'type': 'STRING'},
    {'name': 'video_url', 'type': 'STRING'},
    {'name': 'photo_url', 'type': 'STRING'},
    {'name': 'photo_width', 'type': 'INTEGER'},
    {'name': 'photo_height', 'type': 'INTEGER'},
    {'name': 'post_score', 'type': 'FLOAT'},
    {'name': 'post_like', 'type': 'INTEGER'},
    {'name': 'date_post', 'type': 'DATE'}]

TABLE_SCHEMA_POST = [
    {'name': 'account_id', 'type': 'STRING'},
    {'name': 'account_name', 'type': 'STRING'},
    {'name': 'account_handle', 'type': 'STRING'},
    {'name': 'account_subscriber', 'type': 'INTEGER'},
    {'name': 'account_profile_picture', 'type': 'STRING'},
    {'name': 'account_url', 'type': 'STRING'},
    {'name': 'account_verified', 'type': 'BOOL'},
    {'name': 'account_language', 'type': 'STRING'},
    {'name': 'post_type', 'type': 'STRING'},
    {'name': 'post_description', 'type': 'STRING'},
    {'name': 'post_url', 'type': 'STRING'},
    {'name': 'video_url', 'type': 'STRING'},
    {'name': 'photo_url', 'type': 'STRING'},
    {'name': 'photo_width', 'type': 'INTEGER'},
    {'name': 'photo_height', 'type': 'INTEGER'},
    {'name': 'post_score_2', 'type': 'FLOAT'},
    {'name': 'post_score_3', 'type': 'FLOAT'},
    {'name': 'post_score_5', 'type': 'FLOAT'},
    {'name': 'post_score_7', 'type': 'FLOAT'},
    {'name': 'post_score_15', 'type': 'FLOAT'},
    {'name': 'post_score_30', 'type': 'FLOAT'},
    {'name': 'post_like_2', 'type': 'INTEGER'},
    {'name': 'post_like_3', 'type': 'INTEGER'},
    {'name': 'post_like_5', 'type': 'INTEGER'},
    {'name': 'post_like_7', 'type': 'INTEGER'},
    {'name': 'post_like_15', 'type': 'INTEGER'},
    {'name': 'post_like_30', 'type': 'INTEGER'},
    {'name': 'post_comment_2', 'type': 'INTEGER'},
    {'name': 'post_comment_3', 'type': 'INTEGER'},
    {'name': 'post_comment_5', 'type': 'INTEGER'},
    {'name': 'post_comment_7', 'type': 'INTEGER'},
    {'name': 'post_comment_15', 'type': 'INTEGER'},
    {'name': 'post_comment_30', 'type': 'INTEGER'},
    {'name': 'date_post', 'type': 'DATE'}]

TABLE_SCHEMA_LEADER = [
                {'name': 'id', 'type': 'STRING'},
                {'name': 'name', 'type': 'STRING'},
                {'name': 'handle', 'type': 'STRING'},
                {'name': 'subscriber', 'type': 'INTEGER'},
                {'name': 'interaction', 'type': 'INTEGER'},
                {'name': 'post', 'type': 'INTEGER'},
                {'name': 'interaction_rate', 'type': 'FLOAT'},
                {'name': 'favorite', 'type': 'INTEGER'},
                {'name': 'comment', 'type': 'INTEGER'},
                {'name': 'album_interaction', 'type': 'INTEGER'},
                {'name': 'album_post', 'type': 'INTEGER'},
                {'name': 'album_interaction_rate', 'type': 'FLOAT'},
                {'name': 'album_favorite', 'type': 'INTEGER'},
                {'name': 'album_comment', 'type': 'INTEGER'},
                {'name': 'photo_interaction', 'type': 'INTEGER'},
                {'name': 'photo_post', 'type': 'INTEGER'},
                {'name': 'photo_interaction_rate', 'type': 'FLOAT'},
                {'name': 'photo_favorite', 'type': 'INTEGER'},
                {'name': 'photo_comment', 'type': 'INTEGER'},
                {'name': 'video_interaction', 'type': 'INTEGER'},
                {'name': 'video_post', 'type': 'INTEGER'},
                {'name': 'video_interaction_rate', 'type': 'FLOAT'},
                {'name': 'video_favorite', 'type': 'INTEGER'},
                {'name': 'video_comment', 'type': 'INTEGER'},
                {'name': 'date', 'type': 'DATE'},
            ]

CT_TOKEN = 'EWLzPy6YDwbDpcZ1LNiT0l2FC9HwKUBiXvjqyPGX'
HEADER = {'x-api-token': CT_TOKEN}
TOKEN_TELEGRAM = '5393351877:AAGUfRG3WY5sbQcp2aaGB_9Qx2dkXDeJF9o'
CHAT_ID_TELEGRAM = '@onitifications_devs'
